repos:
  - repo: local
    hooks:
      - id: check-fmt
        name: Run tex-fmt
        entry: bash -c 'nix build .#checks.x86_64-linux.tex-fmt'
        language: system
      - id: check-lint
        name: Run Chktex
        entry: bash -c 'nix build .#checks.x86_64-linux.chktex'
        language: system
