name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  LaTeX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key:
            nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never
      - name: Format
        run: |
          nix build .#checks.x86_64-linux.tex-fmt
      - name: Lint
        run: |
          nix build .#checks.x86_64-linux.chktex
      - name: Build
        run: |
          nix build
      - name: Ensure committed resume matches build output
        run: |
          if ! diff -q resume.pdf result/resume.pdf >/dev/null; then
              echo "PDFs differ"
              exit 1
          fi
